#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# replace with your slack webhook
slack_webhook=

app_directory=$1
app_name=$2

# comprobar que se le pasa el argumento con la ruta del proyecto web de indaga-analytics
if [[ $1 == "" ]]; then
   echo "No se ha indicado el directorio del proyecto para aplicar el autocommit: `date +%F-%T`"
   exit;
fi

# comprobar que existe el directorio de analytics
if [[ ! -d $app_directory ]]; then
  $SCRIPT_DIR/func/slack_pull $slack_webhook $app_name
else
  # acceder al directorio de analytics
  cd $app_directory || exit 1
  # se hace un git pull para mantener el proyecto sincronizado
  git pull && $SCRIPT_DIR/func/slack_pull $slack_webhook $app_name /dev/null 2>&1
fi
