#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# replace with your slack webhook
slack_webhook=$(printenv SLACK_WEBHOOK_URL_DEPLOY)

# app pull message
app_directory=$1
app_name=$2

# verify command args
if [[ $2 == "" ]]; then
   echo "Bad arguments for script execution ${pull}"
   exit;
fi

# check directory exists
if [[ ! -d $app_directory ]]; then
  echo "${app_directory} was not found"
else
  # acceder al directorio de analytics
  cd $app_directory || exit 1
  # se hace un git pull para mantener el proyecto sincronizado
  git pull && \
	$SCRIPT_DIR/func/slack_pull $slack_webhook $app_name /dev/null 2>&1
fi
