#!/bin/bash

APP_SLACK_WEBHOOK=$1
app_deployed=$2
deploy_date_time=$(date +%T)

curl --silent --data-urlencode \
    "$(printf 'payload={"text": "%s pull from remote repository at %s" }' \
        "${app_deployed}" \
        "${deploy_date_time}" \
    )" \
    ${APP_SLACK_WEBHOOK} || true
